-- Real-Time Timetable, Vacant Period & Extra Class Management System
-- Source of truth: attached relational schema and Chen ER model.

create table public.timetable (
  timetable_id bigint generated by default as identity primary key,
  semester varchar(20) not null,
  academic_year varchar(20) not null,
  version integer not null check (version > 0),
  status varchar(12) not null check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  published_at timestamptz,
  unique (semester, academic_year, version),
  check (
    (status = 'PUBLISHED' and published_at is not null)
    or status <> 'PUBLISHED'
  )
);

create table public.section (
  section_id bigint generated by default as identity primary key,
  section_name varchar(50) not null,
  year integer not null check (year > 0),
  program varchar(100) not null
);

create table public.batch (
  batch_id bigint generated by default as identity primary key,
  batch_name varchar(30) not null,
  section_id bigint not null references public.section(section_id),
  unique (section_id, batch_name)
);

create table public.student (
  student_id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(150) not null unique,
  section_id bigint not null references public.section(section_id),
  batch_id bigint references public.batch(batch_id)
);

create table public.faculty (
  faculty_id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(150) not null unique,
  department varchar(100) not null
);

create table public.course (
  course_id bigint generated by default as identity primary key,
  course_name varchar(120) not null,
  credits integer not null check (credits > 0)
);

create table public.room (
  room_id bigint generated by default as identity primary key,
  room_number varchar(30) not null unique,
  room_type varchar(30) not null,
  capacity integer not null check (capacity > 0),
  status varchar(20) not null check (status in ('AVAILABLE', 'MAINTENANCE'))
);

create table public.time_slot (
  slot_id bigint generated by default as identity primary key,
  start_time time not null,
  end_time time not null,
  check (start_time < end_time),
  unique (start_time, end_time)
);

create table public.teaching_assignment (
  assignment_id bigint generated by default as identity primary key,
  faculty_id bigint not null references public.faculty(faculty_id),
  course_id bigint not null references public.course(course_id),
  section_id bigint not null references public.section(section_id),
  batch_id bigint references public.batch(batch_id),
  unique nulls not distinct (faculty_id, course_id, section_id, batch_id)
);

create table public.elective_group (
  group_id bigint generated by default as identity primary key,
  course_id bigint not null references public.course(course_id),
  group_name varchar(100) not null,
  unique (course_id, group_name)
);

create table public.student_course (
  enrollment_id bigint generated by default as identity primary key,
  student_id bigint not null references public.student(student_id),
  course_id bigint not null references public.course(course_id),
  group_id bigint references public.elective_group(group_id),
  unique nulls not distinct (student_id, course_id, group_id)
);

create table public.class_session (
  class_id bigint generated by default as identity primary key,
  timetable_id bigint not null references public.timetable(timetable_id),
  course_id bigint not null references public.course(course_id),
  faculty_id bigint not null references public.faculty(faculty_id),
  section_id bigint references public.section(section_id),
  batch_id bigint references public.batch(batch_id),
  group_id bigint references public.elective_group(group_id),
  room_id bigint not null references public.room(room_id),
  slot_id bigint not null references public.time_slot(slot_id),
  class_date date,
  class_type varchar(25) not null
    check (class_type in ('REGULAR', 'EXTRA', 'VACANCY_UTILIZATION')),
  status varchar(15) not null
    check (status in ('SCHEDULED', 'CANCELLED', 'COMPLETED')),
  reschedule_of bigint references public.class_session(class_id),
  vacancy_of bigint references public.class_session(class_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (reschedule_of is null or reschedule_of <> class_id),
  check (vacancy_of is null or vacancy_of <> class_id),
  check (
    (class_type = 'VACANCY_UTILIZATION' and vacancy_of is not null)
    or (class_type <> 'VACANCY_UTILIZATION' and vacancy_of is null)
  )
);

create table public.vacant_slot_claim (
  claim_id bigint generated by default as identity primary key,
  class_id bigint not null references public.class_session(class_id),
  faculty_id bigint not null references public.faculty(faculty_id),
  course_id bigint not null references public.course(course_id),
  section_id bigint not null references public.section(section_id),
  claimed_at timestamptz not null default now(),
  claim_deadline timestamptz not null,
  status varchar(12) not null
    check (status in ('OPEN', 'CLAIMED', 'EXPIRED', 'CANCELLED')),
  check (claimed_at < claim_deadline or status in ('EXPIRED', 'CANCELLED'))
);

create unique index one_successful_claim_per_cancelled_session
  on public.vacant_slot_claim(class_id)
  where status = 'CLAIMED';

create table public.notification (
  notification_id bigint generated by default as identity primary key,
  student_id bigint references public.student(student_id),
  faculty_id bigint references public.faculty(faculty_id),
  class_id bigint not null references public.class_session(class_id),
  notification_type varchar(30) not null
    check (
      notification_type in (
        'CLASS_CANCELLED',
        'VACANT_SLOT_AVAILABLE',
        'VACANT_SLOT_CLAIMED',
        'EXTRA_CLASS',
        'CLASS_RESCHEDULED',
        'CLASS_UPDATED'
      )
    ),
  message text not null,
  created_at timestamptz not null default now(),
  is_read boolean not null default false,
  check ((student_id is null) <> (faculty_id is null))
);

create index class_session_date_slot_idx
  on public.class_session(class_date, slot_id);
create index class_session_faculty_idx
  on public.class_session(faculty_id, class_date);
create index class_session_section_idx
  on public.class_session(section_id, class_date);
create index notification_student_idx
  on public.notification(student_id, is_read, created_at desc);
create index notification_faculty_idx
  on public.notification(faculty_id, is_read, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger class_session_touch_updated_at
before update on public.class_session
for each row execute function public.touch_updated_at();

create or replace function public.validate_batch_section()
returns trigger
language plpgsql
as $$
declare
  owning_section bigint;
begin
  if new.batch_id is null then
    return new;
  end if;

  select section_id into owning_section
  from public.batch
  where batch_id = new.batch_id;

  if owning_section is distinct from new.section_id then
    raise exception 'Batch % does not belong to section %', new.batch_id, new.section_id;
  end if;

  return new;
end;
$$;

create trigger student_batch_matches_section
before insert or update of batch_id, section_id on public.student
for each row execute function public.validate_batch_section();

create trigger assignment_batch_matches_section
before insert or update of batch_id, section_id on public.teaching_assignment
for each row execute function public.validate_batch_section();

create trigger session_batch_matches_section
before insert or update of batch_id, section_id on public.class_session
for each row execute function public.validate_batch_section();

create or replace function public.current_user_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.current_faculty_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select faculty_id
  from public.faculty
  where lower(email) = public.current_user_email()
  limit 1;
$$;

create or replace function public.current_student_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select student_id
  from public.student
  where lower(email) = public.current_user_email()
  limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select upper(coalesce(auth.jwt() -> 'user_metadata' ->> 'role', '')) = 'ADMIN';
$$;

create or replace function public.scope_strength(
  p_section_id bigint,
  p_batch_id bigint,
  p_group_id bigint
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.student s
  where s.section_id = p_section_id
    and (p_batch_id is null or s.batch_id = p_batch_id)
    and (
      p_group_id is null
      or exists (
        select 1
        from public.student_course sc
        where sc.student_id = s.student_id
          and sc.group_id = p_group_id
      )
    );
$$;

create or replace function public.claim_vacant_slot(
  p_class_id bigint,
  p_course_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  claimant_id bigint := public.current_faculty_id();
  cancelled_session public.class_session%rowtype;
  selected_slot public.time_slot%rowtype;
  selected_room public.room%rowtype;
  claim_deadline timestamptz;
  replacement_id bigint;
  affected_strength integer;
begin
  if claimant_id is null then
    raise exception 'Authenticated user is not a faculty member';
  end if;

  select * into cancelled_session
  from public.class_session
  where class_id = p_class_id
  for update;

  if not found or cancelled_session.status <> 'CANCELLED' then
    raise exception 'Vacancy must reference a cancelled class session';
  end if;

  if exists (
    select 1
    from public.class_session
    where reschedule_of = cancelled_session.class_id
  ) then
    raise exception 'A rescheduled session does not create a claimable vacancy';
  end if;

  if cancelled_session.class_date is null or cancelled_session.section_id is null then
    raise exception 'Cancelled session requires a date and section to be claimed';
  end if;

  select * into selected_slot
  from public.time_slot
  where slot_id = cancelled_session.slot_id;

  claim_deadline :=
    (cancelled_session.class_date + selected_slot.start_time)
      at time zone 'Asia/Kolkata';

  if now() >= claim_deadline then
    raise exception 'Claim deadline has passed';
  end if;

  if exists (
    select 1
    from public.vacant_slot_claim
    where class_id = p_class_id and status = 'CLAIMED'
  ) then
    raise exception 'Vacancy was already claimed';
  end if;

  if not exists (
    select 1
    from public.teaching_assignment ta
    where ta.faculty_id = claimant_id
      and ta.course_id = p_course_id
      and ta.section_id = cancelled_session.section_id
      and (
        cancelled_session.batch_id is null
        or ta.batch_id is null
        or ta.batch_id = cancelled_session.batch_id
      )
  ) then
    raise exception 'Faculty is not assigned to this course and section scope';
  end if;

  select * into selected_room
  from public.room
  where room_id = cancelled_session.room_id
  for share;

  if selected_room.status <> 'AVAILABLE' then
    raise exception 'Room is not available';
  end if;

  affected_strength := public.scope_strength(
    cancelled_session.section_id,
    cancelled_session.batch_id,
    cancelled_session.group_id
  );

  if affected_strength > selected_room.capacity then
    raise exception 'Room capacity is insufficient';
  end if;

  if exists (
    select 1
    from public.class_session cs
    join public.time_slot ts on ts.slot_id = cs.slot_id
    where cs.class_date = cancelled_session.class_date
      and cs.status = 'SCHEDULED'
      and cs.class_id <> cancelled_session.class_id
      and ts.start_time < selected_slot.end_time
      and ts.end_time > selected_slot.start_time
      and (
        cs.faculty_id = claimant_id
        or cs.room_id = cancelled_session.room_id
        or (
          cs.section_id = cancelled_session.section_id
          and (
            cancelled_session.batch_id is null
            or cs.batch_id is null
            or cs.batch_id = cancelled_session.batch_id
          )
          and (
            cancelled_session.group_id is null
            or cs.group_id is null
            or cs.group_id = cancelled_session.group_id
          )
        )
      )
  ) then
    raise exception 'Scheduling conflict detected for the actual time range';
  end if;

  insert into public.vacant_slot_claim (
    class_id,
    faculty_id,
    course_id,
    section_id,
    claimed_at,
    claim_deadline,
    status
  ) values (
    cancelled_session.class_id,
    claimant_id,
    p_course_id,
    cancelled_session.section_id,
    now(),
    claim_deadline,
    'CLAIMED'
  );

  insert into public.class_session (
    timetable_id,
    course_id,
    faculty_id,
    section_id,
    batch_id,
    group_id,
    room_id,
    slot_id,
    class_date,
    class_type,
    status,
    vacancy_of
  ) values (
    cancelled_session.timetable_id,
    p_course_id,
    claimant_id,
    cancelled_session.section_id,
    cancelled_session.batch_id,
    cancelled_session.group_id,
    cancelled_session.room_id,
    cancelled_session.slot_id,
    cancelled_session.class_date,
    'VACANCY_UTILIZATION',
    'SCHEDULED',
    cancelled_session.class_id
  )
  returning class_id into replacement_id;

  insert into public.notification (
    student_id,
    class_id,
    notification_type,
    message
  )
  select
    s.student_id,
    replacement_id,
    'VACANT_SLOT_CLAIMED',
    'A vacant period was claimed and a replacement class was scheduled.'
  from public.student s
  where s.section_id = cancelled_session.section_id
    and (
      cancelled_session.batch_id is null
      or s.batch_id = cancelled_session.batch_id
    )
    and (
      cancelled_session.group_id is null
      or exists (
        select 1
        from public.student_course sc
        where sc.student_id = s.student_id
          and sc.group_id = cancelled_session.group_id
      )
    );

  insert into public.notification (
    faculty_id,
    class_id,
    notification_type,
    message
  ) values (
    claimant_id,
    replacement_id,
    'VACANT_SLOT_CLAIMED',
    'Your vacancy claim succeeded and the replacement class was created.'
  );

  return replacement_id;
end;
$$;

alter table public.timetable enable row level security;
alter table public.student enable row level security;
alter table public.section enable row level security;
alter table public.batch enable row level security;
alter table public.faculty enable row level security;
alter table public.course enable row level security;
alter table public.room enable row level security;
alter table public.time_slot enable row level security;
alter table public.teaching_assignment enable row level security;
alter table public.elective_group enable row level security;
alter table public.student_course enable row level security;
alter table public.class_session enable row level security;
alter table public.vacant_slot_claim enable row level security;
alter table public.notification enable row level security;

create policy reference_data_read on public.section for select to authenticated using (true);
create policy batch_read on public.batch for select to authenticated using (true);
create policy course_read on public.course for select to authenticated using (true);
create policy room_read on public.room for select to authenticated using (true);
create policy slot_read on public.time_slot for select to authenticated using (true);
create policy elective_read on public.elective_group for select to authenticated using (true);
create policy published_timetable_read on public.timetable for select to authenticated
  using (status = 'PUBLISHED' or public.is_admin());

create policy student_self_or_admin on public.student for select to authenticated
  using (student_id = public.current_student_id() or public.is_admin());

create policy faculty_self_or_admin on public.faculty for select to authenticated
  using (faculty_id = public.current_faculty_id() or public.is_admin());

create policy assignment_scoped_read on public.teaching_assignment for select to authenticated
  using (faculty_id = public.current_faculty_id() or public.is_admin());

create policy enrollment_scoped_read on public.student_course for select to authenticated
  using (student_id = public.current_student_id() or public.is_admin());

create policy session_scoped_read on public.class_session for select to authenticated
  using (
    public.is_admin()
    or faculty_id = public.current_faculty_id()
    or exists (
      select 1
      from public.student s
      where s.student_id = public.current_student_id()
        and s.section_id = class_session.section_id
        and (class_session.batch_id is null or s.batch_id = class_session.batch_id)
        and (
          class_session.group_id is null
          or exists (
            select 1
            from public.student_course sc
            where sc.student_id = s.student_id
              and sc.group_id = class_session.group_id
          )
        )
    )
    or (
      status = 'CANCELLED'
      and exists (
        select 1
        from public.teaching_assignment ta
        where ta.faculty_id = public.current_faculty_id()
          and ta.section_id = class_session.section_id
          and (
            class_session.batch_id is null
            or ta.batch_id is null
            or ta.batch_id = class_session.batch_id
          )
      )
    )
  );

create policy claim_scoped_read on public.vacant_slot_claim for select to authenticated
  using (faculty_id = public.current_faculty_id() or public.is_admin());

create policy notification_recipient_read on public.notification for select to authenticated
  using (
    student_id = public.current_student_id()
    or faculty_id = public.current_faculty_id()
    or public.is_admin()
  );

create policy notification_recipient_update on public.notification for update to authenticated
  using (
    student_id = public.current_student_id()
    or faculty_id = public.current_faculty_id()
  )
  with check (
    student_id = public.current_student_id()
    or faculty_id = public.current_faculty_id()
  );

grant execute on function public.claim_vacant_slot(bigint, bigint) to authenticated;
